# Generated by Django 4.1.7 on 2023-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_vendorcredit_vendorcreditinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('gst_treatment', models.CharField(max_length=255)),
                ('source_supply', models.CharField(max_length=255)),
                ('credit_note', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('credit_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorcreditinvoice',
            name='inv',
        ),
        migrations.DeleteModel(
            name='VendorCredit',
        ),
        migrations.DeleteModel(
            name='VendorCreditInvoice',
        ),
    ]
