# Generated by Django 4.1.7 on 2023-06-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_vendorcredit_vendor_invoice_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor_invoice_item',
        ),
    ]
